# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 2d7035e6e74081f5c89465ffc24c5da93182d3a3ec7a9a6f3b5f47847bd541a05f0ed03238ccc010733a349ba7fb411ddab74a3fe0ca2e1fbe4514b5fa64542a

test:
  secret_key_base: b0a83238c1a80617c1e722d4104b56e2dca159011e5f1575045badb4cf366485c08f6f47afed410f9a94c795cf16e929e31bbc94c8e3b6ef4d9f34b50f61a82d

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
